### PR TITLE
trying to update to node 20 

### PR DESCRIPTION
**Pull request by Donostio**
Hoping this means the script can work again - using node 20

### CODE REVIEW

**Comment by cecobask** [comment]
Hi @Donostio, I just fixed this issue now.
You can take a look at the latest commit on the main branch for information what needed to be updated 👍 
Thank you for reporting it!

**Comment by Donostio** [comment]
Thank you for such a fast reply.

I coped across your two new workflow files.

I seem to have run into further issues - please see log below. In secretes
for the lists ID i have entered 'all' is this a problem or is it the two
IMDB cookies I have copied across? what do you think?
##[debug]Evaluating: success() ##[debug]Evaluating success: ##[debug]=>
true ##[debug]Result: true ##[debug]Starting: Sync ##[debug]Loading inputs
##[debug]Loading env Run ./build/syncer ##[debug]/usr/bin/bash -e
/home/runner/work/_temp/8be9101e-8a19-40ce-bc19-d26a92e4b2ac.sh
{"time":"2024-02-19T15:49:02.621922574Z","level":"ERROR","source":{"function":"
github.com/cecobask/imdb-trakt-sync/pkg/syncer.NewSyncer","file":"/home/runner/work/imdb-trakt-sync/imdb-trakt-sync/pkg/syncer/syncer.go","line":70},"msg":"failure
hydrating imdb client","error":"failure scraping imdb user id: imdb user id
not found: failure scraping imdb response for selector .user-profile.userId
and attribute data-userid"} Error: Process completed with exit code 1.
##[debug]Finishing: Sync


Many thanks
Gary

**Comment by cecobask** [comment]
> In secretes for the lists ID i have entered 'all' is this a problem or is it the two IMDB cookies I have copied across?

Yes, that's fine. Just make sure you haven't quoted the value, it should be just `all`.

Based on the output of your latest `sync` job runs, it looks like the problem is related to your IMDB secret values:
```json
{
   "time":"2024-02-19T16:22:30.112654791Z",
   "level":"ERROR",
   "source":{
      "function":"github.com/cecobask/imdb-trakt-sync/pkg/syncer.NewSyncer",
      "file":"/home/runner/work/imdb-trakt-sync/imdb-trakt-sync/pkg/syncer/syncer.go",
      "line":70
   },
   "msg":"failure hydrating imdb client",
   "error":"failure scraping imdb user id: imdb user id not found: failure scraping imdb response for selector .user-profile.userId and attribute data-userid"
}
```

Double check you have valid values for all secrets and try to rerun the workflow.

**Comment by Donostio** [comment]
Hi
Yes, I re-entered all of the secret values the number of times and then I
set up a brand new fork with your new version and entered the secrets again
- but I've got the same error.

I noticed that a previous version of your code used the actual ur number
for the IDBM user ID and the current version scrapes it using the
cookies. But something's going wrong. Is using teh UR-number still an
option?

Kind regards
Gary

**Comment by cecobask** [comment]
> Yes, I re-entered all of the secret values the number of times and then I set up a brand new fork with your new version and entered the secrets again - but I've got the same error

I recommend keeping the fork up to date instead of creating clones.
It's easier to sync that way, whenever there are updates.
I can see the main branch is showing this message, which means its history has diverged:

>This branch is [4 commits ahead of](https://github.com/Donostio/imdb-trakt-sync/compare/cecobask%3Aimdb-trakt-sync%3Amain...main), [1 commit behind](https://github.com/Donostio/imdb-trakt-sync/compare/main...cecobask%3Aimdb-trakt-sync%3Amain) cecobask/imdb-trakt-sync:main.

---

> I noticed that a previous version of your code used the actual ur number for the IDBM user ID and the current version scrapes it using the cookies. But something's going wrong. Is using teh UR-number still an option?

That's correct. The initial version of imdb-trakt-sync required the users to enter their ID manually.
This required more work and proved to be error-prone, so I automated it with web scraping.
I believe the IMDb website should be the same for anybody and I'm 90% certain the problem stems from the IMDb cookies.

I can assist you in setting up the repository, but I cannot debug it without using the same cookies as you.
That being said, do not share any sensitive data here as it may get your IMDb account compromised.
You can email me at baskski@gmail.com and we can sort it out together.

**Comment by Donostio** [comment]
That's very kind, thank you. I will email you later tonight (I'm on a
mobile device now) when I can copy the cookie again.

I'm happy to share my IMDB log-in details with you, and the two cookies I
am using. Hopefully, that will reveal the issue?

**Pull request closed without merging**
